
########################## 简化配置 ##########################

#zuul:
#  routes:
#    client-a:
#      path: /client/**
#      serviceId: client-a

#单实例serviceid映射
zuul:
  routes:
    client-a: /client/**