
########################## 映射覆盖情况 ##########################


#总会路由到最后面的那个服务 client-a
zuul:
  routes:
    client-b:
      path: /client/**
      serviceId: client-b
    client-a:
      path: /client/**
      serviceId: client-a